apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: default
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins-server
  type: ClusterIP  
  ports:
    - port: 80
      targetPort: 8080
      
