apiVersion: v1
kind: Pod
metadata:
  name: test-dbpodalp
spec:
  containers:
  - name: efs-container
    image: 635304474566.dkr.ecr.us-east-1.amazonaws.com/examplepod-puntonet:alplatest
    command: ["/bin/sh"]
    args: ["-c", "sleep 1000000"]