# Jenkins master: https://digitalavenue.dev/How-To-Setup-Jenkins-On-Kubernetes/
# Slaves https://www.devopsart.com/2020/08/step-by-steps-for-jenkins-dynamically.html
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: default
  annotations:
     eks.amazonaws.com/role-arn: arn:aws:iam::793764525616:role/adminaccess
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: default
---