# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: ebs-sc
# provisioner: ebs.csi.aws.com
# volumeBindingMode: WaitForFirstConsumer

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins-pv2
  
# spec:
#   storageClassName: ebs-sc
#   claimRef:
#     name: jenkins-pvc2
#     namespace: default
#   capacity:
#     storage: 3Gi
#   accessModes:
#     - ReadWriteOnce
#   csi:
#       driver: ebs.csi.aws.com
#       fsType: ext4
      
#   #     volumeHandle: vol-040c4592907cd13b6
  
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jenkins-pvc2
#   namespace: default
# spec:
#   storageClassName: ebs-sc
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 3Gi

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: generic
  annotations:
   storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2  
  iopsPerGB: "10" 
  fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prueba-jenkins2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: generic
  resources:
    requests:
      storage: 4Gi
