apiVersion: v1
kind: Service
metadata:
  
  name: jenkins-lb
  namespace: default
  
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins-server
  sessionAffinity: None
  type: ClusterIP
